### ISSUE TITLE
Milestone 0.2.0

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib-ai-chat-extension#23]
@igoogolx 最近我在高强度使用这个插件，发现一些还可以优化的地方。

- [x] 替换 PDF.js 为 muPDF，寻求更好的性能。现在如果我们不使用 LLAMAParse API，我们使用 PDF.js 来读取论文的文本。现在的计划是 Paperlib 的主体和各个插件，全面摒弃掉 PDF.js 换为 muPDF。因为性能更好，而且他的 API 对比于 PDF.js 简直太清晰易用好维护了。
- [x] 论文载入进度：现在论文载入的时候，显示的是一个提示loading，加上个一直转圈。但是有的论文载入时间还是比较长的，我想能否显示论文载入的进度。这样读者在等待的时候，心里有数。而不是认为插件卡死了。这需要做：
  - [x] 可能需要我们首先做好 PDF 分页。
  - [x] 把分好的页给依次提交给 LLAMAParse API 或者 muPDF 解析文本，在每页解析过后，更新进度条。

不用太着急，抽空慢慢一个一个做就好。感谢！

**Comment by igoogolx** [comment]
有几个比较大的改动：

- Setting 新增 Disable Cache 配置，允许用户清除并禁用所有缓存
- 当 Paper 没有解析成功时， Chat 窗口不会同步主窗口选中的 Paper, 确保一次只会有一个在解析 
- Paper 的解析进度分为两部分：Get Full Text 和 Embed，各占 50% 的进度
- Get Full Text 有两种模式
- Mupdf 本地解析：逐页解析，每一页都会更新进度
- Mupdf 分页+Llama解析：逐页解析的效率太低，所以会分为三次解析，一次至少解析两页。例如一份 9 页的 Paper，每次解析 3 页

功能都已经开发完成了，还需要再测试下。另外现在的进度条功能，我不太确定是否合理，你可以先试用下。我们确定没问题之后，再合并 PR。

**Comment by GeoffreyChen777** [comment]
太牛啦！！我会抽空测试下，万分感谢！

**Comment by GeoffreyChen777** [comment]
1. 我测试了进度显示，我认为现在这样用文字显示就足够了。
2. 关于 disable cache 我觉得可能可以稍微改一下逻辑。现在的是需要用户disable，再打开一个新论文的时候，才会触发 reset。但是我想这个功能对应的场景需求应该是，cache有错误，或者 cache 质量不好，我想重新解析一下 pdf，所以需要删除掉原来的cache。基本不会有人拒绝 cache 吧。如果是这样的话，按照目前的逻辑，我就需要，首先 disable，然后打开一个论文 chat 触发reset，然后回去设置 enable。之后才能让其他论文继续 cache。所以我觉得可以这样修改一下：
  - 在插件 preference 里存一个`type: hidden`的项，比如叫做`require-cache-reset`. `type` 是可以是 `hidden` 来让UI不显示的。然后当用户的`disable-cache` 从 `false` 变为 `true` 的时候，代表着用户想要 reset cache。此时，设置 `require-cache-reset` 为 `true`。你可以在 `ext/src/main.ts` 里很容易监听这个变化。
  - 在 `view/src/utils/persist.ts` 里，判断要不要 resetCache 使用 `require-cache-reset`，当 reset 了之后，重新设置它为`false`。`disable-cache` 判断的应该是需不需要创建 cache，而不是需不需要 reset。

**Comment by igoogolx** [comment]
我理解你的意思。其实我是想把 `disable-cache` 做成 Button 的，因为它应该是一次性触发的动作，但是 preference 的 `type` 好像不支持 Button, 所以用 Switch 替代了。请问下 preference 的 `type`  能支持 Button 吗？

**Comment by GeoffreyChen777** [comment]
是这样的，就是个switch替代button的方案。

目前paperlib主体没写button的组件。如果实现了之后就可以用button啦。如果你想写这个组件，可以直接 PR paperlib，具体在这个地方：

https://github.com/Future-Scholars/paperlib/blob/main/app/renderer/ui/preference-view/components/extension-setting.vue

**Comment by igoogolx** [comment]
我提了 [PR](https://github.com/Future-Scholars/paperlib/pull/606) 来在 preference  支持 Button，paperlib-api 需要发新版本。

**Comment by igoogolx** [comment]
Hi, 虽然 paperlib 的 [PR ](https://github.com/Future-Scholars/paperlib/pull/606) 已经合并了，但是 0.2.0 需要新版的 paperlib-api，麻烦有空发下。

**Comment by GeoffreyChen777** [comment]
嗯嗯我这个月底要交博士毕业论文，所以我先弄完论文，然后弄这个。

**Comment by GeoffreyChen777** [comment]
@igoogolx hello 好久不见，实在抱歉拖了很久。前两天刚博士答辩完，然后搬家到了新城市。现在时间稍微宽松些来。我已经发布了新的 paperlib-api。

**Comment by igoogolx** [comment]
不好意思，消息淹掉了，今天刚看到，时间确实有点久了哈哈😂。
我这两天会整理下之前 PR，准备 0.2.0 版本。

**Comment by GeoffreyChen777** [comment]
hh好的没问题👍🏻

**Comment by igoogolx** [comment]
@GeoffreyChen777 Hi, 我升级了项目的依赖，最大的变化是 transformers.js 从 v2 升级到 v3。v3 已经支持了 webgpu，不过我没有开启，因为现在的计算量不是很大，估计提升不会明显，未来可以考虑增加本地 task 的计算量。PR 可以 review 了，没问题的话，就可以发布 0.2.0 了。

**Comment by GeoffreyChen777** [comment]
@igoogolx 感谢感谢！
